name: Run CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_debug:
    name: Build Debug
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_debug -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build_debug

    - name: Upload binaries 
      uses: actions/upload-artifact@v4
      with:
        name: build_debug
        path: ${{github.workspace}}/build_debug


  build_tsan:
    name: Build TSAN
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_tsan -DCMAKE_BUILD_TYPE=TSAN

    - name: Build
      run: cmake --build ${{github.workspace}}/build_tsan

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: build_tsan
        path: ${{github.workspace}}/build_tsan


  test_debug:
    name: Run tests and save coverage
    runs-on: ubuntu-latest
    needs: build_debug

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: build_debug
        path: ${{github.workspace}}/build_debug

    - name: Fix permissions
      run: chmod -R +x build_debug

    - name: Test
      working-directory: ${{github.workspace}}/build_debug
      run: ctest

    - name: Run lcov
      if: "always()"
      run: lcov --directory ${{github.workspace}}/build_debug --capture --output-file ${{github.workspace}}/build_debug/coverage.info --ignore-errors mismatch --rc branch_coverage=1 --include src/storage.h

    - name: Upload coverage info
      uses: actions/upload-artifact@v4
      if: "always()"
      with:
        name: coverage_info
        path: ${{github.workspace}}/build_debug/coverage.info


  test_tsan:
    name: Run tests with TSAN
    runs-on: ubuntu-latest
    needs: build_tsan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: build_tsan
        path: ${{github.workspace}}/build_tsan

    - name: Fix permissions
      run: chmod -R +x build_tsan

    - name: Test
      working-directory: ${{github.workspace}}/build_tsan
      run: ctest


  coverage_report:
    name: Generate coverage report
    needs: test_debug
    runs-on: ubuntu-latest
    if: "always()"

    permissions:
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Download coverage info
      uses: actions/download-artifact@v4
      with:
        name: coverage_info
        path: ${{github.workspace}}

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: ${{github.workspace}}/coverage.info
        minimum-coverage: 70
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true


  static_analyzer:
    name: Cppcheck (Static Analyzer)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: ${{github.workspace}}/cppcheck-results.txt
          other_options: '-Isrc'

      - name: Upload analyzer report
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-results.txt
          path: ${{github.workspace}}/cppcheck-results.txt